import logging
from pathlib import Path
from typing import List, Dict, Any

logger = logging.getLogger("video_engine.captions.ass_builder")

def format_ass_time(seconds: float) -> str:
    """Formats a float time in seconds into ASS time format: H:MM:SS.cs"""
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centiseconds = int(round((seconds % 1) * 100))
    
    if centiseconds == 100:
        secs += 1
        centiseconds = 0
    if secs == 60:
        minutes += 1
        secs = 0
    if minutes == 60:
        hours += 1
        minutes = 0
        
    return f"{hours}:{minutes:02d}:{secs:02d}.{centiseconds:02d}"

def build_ass_file(words: List[Dict[str, Any]], output_path: Path, font_name: str = "Arial", font_size: int = 64) -> Path:
    """
    Groups word timestamps and writes them into a karaoke ASS file.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    logger.info(f"Generating ASS captions file: {output_path.name}")
    
    # 1. Group words into lines
    # Rules: max 5 words per line, OR if there's a pause of > 0.8 seconds between words, start a new line.
    lines: List[List[Dict[str, Any]]] = []
    current_line: List[Dict[str, Any]] = []
    
    for i, w in enumerate(words):
        if not current_line:
            current_line.append(w)
        else:
            prev_w = current_line[-1]
            pause = w["start"] - prev_w["end"]
            
            if len(current_line) >= 5 or pause > 0.8:
                lines.append(current_line)
                current_line = [w]
            else:
                current_line.append(w)
                
    if current_line:
        lines.append(current_line)

    # 2. Write ASS structure
    with open(output_path, "w", encoding="utf-8") as f:
        # Script Info Section
        f.write("[Script Info]\n")
        f.write("; Script generated by AutoShorts Video Engine\n")
        f.write("ScriptType: v4.00+\n")
        f.write("PlayResX: 1080\n")
        f.write("PlayResY: 1920\n")
        f.write("ScaledBorderAndShadow: yes\n\n")
        
        # Styles Section
        # Colors: &HAABBGGRR (Alpha Blue Green Red in hex)
        # PrimaryColour: White (&H00FFFFFF)
        # SecondaryColour: Bright Yellow (&H0000FFFF) for karaoke highlight
        # OutlineColour: Black (&H00000000)
        # BackColour: Semi-transparent Black (&H80000000)
        # BorderStyle: 3 (opaque box outline)
        # Alignment: 2 (bottom center)
        # MarginV: 280 (vertical safe margin from bottom)
        f.write("[V4+ Styles]\n")
        f.write("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n")
        f.write(f"Style: Default,{font_name},{font_size},&H00FFFFFF,&H0000FFFF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,3,4,0,2,80,80,280,1\n\n")
        
        # Events Section
        f.write("[Events]\n")
        f.write("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n")
        
        for line in lines:
            line_start = line[0]["start"]
            line_end = line[-1]["end"]
            
            # Construct the karaoke text
            text_parts = []
            curr_time = line_start
            
            for w in line:
                word_str = w["word"]
                w_start = w["start"]
                w_end = w["end"]
                
                # Check for gap between previous word and current word
                if w_start > curr_time:
                    gap_cs = int(round((w_start - curr_time) * 100))
                    if gap_cs > 0:
                        text_parts.append(f"{{\\kf{gap_cs}}}")
                
                # Word duration in centiseconds
                dur_cs = max(1, int(round((w_end - w_start) * 100)))
                text_parts.append(f"{{\\kf{dur_cs}}}{word_str} ")
                curr_time = w_end
                
            karaoke_text = "".join(text_parts).strip()
            
            # Format time stamps
            start_str = format_ass_time(line_start)
            end_str = format_ass_time(line_end)
            
            f.write(f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{karaoke_text}\n")
            
    logger.info(f"Successfully generated ASS file with {len(lines)} subtitle lines.")
    return output_path
